### ISSUE TITLE
ics notifications

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#213]
Some users have a setting in their email/calendar client where the .ics reminder file we send after each measure is being recognized and therefore trigers an automatic notification which can be kind of spammy. 

I see two ways of deeling with this issue : 

1/ Fast solution : remove the attached file.

2/ Switch the link to the attach file with a link to an URL where the attached file can be downloaded. This added step will prevent the .ics file to be attached to the mail and therefore won't trigger any notification.

What are your thoughts on that ? Any other suggestions ?

Thanks

**Comment by VS2000** [comment]
I like the second option.

**Comment by MathieuNls** [comment]
We can't store ics files on heroku, they'll be deleted every time we do a new release. We'll have to upload them to a third party online storage and then give access to only one user through a custom link. That's kind of overkill for this option imo. Aren't there any service that propose "add to calendar" links that we could integrate into our emails instead of ics ?

**Comment by AlphonseJr** [comment]
I'll look for such a service, in the meantime, could you remove the link as we are expecting a spike of measures in the next days ;)
